In [11]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [12]:
df = pd.read_csv("data/processed/delhi_cleaned.csv")

df.head()

,datetime,date,year,month,day,hour,day_of_week,is_weekend,season,city,...,no2,so2,co,o3,temperature,humidity,wind_speed,visibility,aqi,aqi_category
0,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,119.6,47.1,5.19,12.3,9.4,100,3.6,1.2,500,Severe
1,2020-01-01 12:00:00,2020-01-01,2020,1,1,12,Wednesday,0,winter,Delhi,...,117.9,39.3,4.32,15.8,20.6,50,5.9,1.4,500,Severe
2,2020-01-01 18:00:00,2020-01-01,2020,1,1,18,Wednesday,0,winter,Delhi,...,150.1,36.3,7.13,14.3,12.4,56,4.5,1.1,500,Severe
3,2020-01-01 23:00:00,2020-01-01,2020,1,1,23,Wednesday,0,winter,Delhi,...,142.0,30.3,4.90,13.2,14.4,48,5.8,1.4,500,Severe
4,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,138.4,41.5,7.56,15.4,6.8,100,2.8,0.4,500,Severe

In [13]:
df['datetime'] = pd.to_datetime(df['datetime'])

df = df.sort_values('datetime')

df.head()

,datetime,date,year,month,day,hour,day_of_week,is_weekend,season,city,...,no2,so2,co,o3,temperature,humidity,wind_speed,visibility,aqi,aqi_category
0,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,119.6,47.1,5.19,12.3,9.4,100,3.6,1.2,500,Severe
52,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,94.7,16.4,4.38,24.5,8.3,100,3.6,1.7,399,Very Poor
48,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,111.2,22.6,5.13,15.2,9.9,100,2.2,1.3,500,Severe
40,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,107.7,23.7,4.67,14.6,6.8,100,3.7,1.4,500,Severe
36,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,122.5,29.2,4.57,14.3,8.8,100,2.2,1.0,500,Severe

In [14]:
df['aqi_lag1'] = df['aqi'].shift(1)

df['aqi_lag3'] = df['aqi'].shift(3)

df['aqi_lag7'] = df['aqi'].shift(7)

In [15]:
df['pm25_roll_mean'] = (

    df['pm25']

    .rolling(7)

    .mean()

)


df['pm25_roll_std'] = (

    df['pm25']

    .rolling(7)

    .std()

)



df['pm10_roll_mean'] = (

    df['pm10']

    .rolling(7)

    .mean()

)



df['pm10_roll_std'] = (

    df['pm10']

    .rolling(7)

    .std()

)

In [16]:
print(df['season'].unique())
encoder = LabelEncoder()

df['season_encoded'] = encoder.fit_transform(df['season'])

<StringArray>
['winter', 'summer', 'monsoon', 'post_monsoon']
Length: 4, dtype: str

In [17]:
encoder2 = LabelEncoder()


df['aqi_category_encoded'] = (

encoder2.fit_transform(

df['aqi_category']

)

)

In [18]:
df['pm_ratio'] = (

df['pm25']

/

df['pm10']

)



df['wind_humidity'] = (

df['wind_speed']

*

df['humidity']

)

In [19]:
df=df.dropna()


print(df.shape)

(122745, 36)

In [20]:
scaler = StandardScaler()


features=[


'pm25',

'pm10',

'no2',

'so2',

'co',

'o3',

'temperature',

'humidity',

'wind_speed',

'visibility',

'aqi_lag1',

'aqi_lag3',

'aqi_lag7',

'pm25_roll_mean',

'pm25_roll_std',

'pm10_roll_mean',

'pm10_roll_std',

'season_encoded',

'aqi_category_encoded',

'pm_ratio',

'wind_humidity'

]


df[features]=scaler.fit_transform(


df[features]

)

In [21]:
df.to_csv(

"data/processed/delhi_featured.csv",

index=False

)


print(

"✅ Feature Engineering Complete"

)

✅ Feature Engineering Complete

In [22]:
print(df.shape)

df.head()

(122745, 36)

,datetime,date,year,month,day,hour,day_of_week,is_weekend,season,city,...,aqi_lag3,aqi_lag7,pm25_roll_mean,pm25_roll_std,pm10_roll_mean,pm10_roll_std,season_encoded,aqi_category_encoded,pm_ratio,wind_humidity
24,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,1.352161,1.352161,1.014612,1.130374,1.035269,1.722115,1.135759,0.734814,-1.226194,-0.999621
20,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,1.352161,0.763291,1.106294,0.190809,1.130946,0.750847,1.135759,0.734814,0.628212,-0.500516
16,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,1.352161,1.352161,1.074515,0.492224,1.153277,0.660327,1.135759,0.734814,-1.560066,-0.605590
12,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,1.352161,1.352161,1.090357,0.386299,1.123750,0.771723,1.135759,0.734814,0.401769,-0.894546
44,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,1.352161,1.352161,1.008894,0.830975,1.031101,1.254721,1.135759,0.734814,0.452098,-0.658128